[project]
name = "model-compare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numerapi>=2.20.6",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "typer>=0.16.0",
    "tabulate>=0.9.0",
]
