name = "numerai-model-reviwer"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-12-05"

# Enable Node.js compatibility for SvelteKit
compatibility_flags = ["nodejs_compat"]
